# Generated by Django 4.1.3 on 2022-12-07 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyc',
            fields=[
                ('level_0', models.BigIntegerField(blank=True, null=True)),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('portal', models.CharField(max_length=700, primary_key=True, serialize=False)),
                ('accucnt', models.FloatField(blank=True, null=True)),
                ('aggrcnt', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('sales', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'buyc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('level_0', models.BigIntegerField(blank=True, null=True)),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=700, primary_key=True, serialize=False)),
                ('context', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('isbn', models.TextField(blank=True, null=True)),
                ('publisher', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'information',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LibDate',
            fields=[
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('pub', models.CharField(max_length=700, primary_key=True, serialize=False)),
                ('pub_year', models.FloatField(blank=True, null=True)),
                ('pub_month', models.FloatField(blank=True, null=True)),
                ('pub_day', models.FloatField(blank=True, null=True)),
                ('pub_date', models.FloatField(blank=True, null=True)),
                ('repub', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lib_date',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LibInformation',
            fields=[
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=700, primary_key=True, serialize=False)),
                ('isbn', models.TextField(blank=True, null=True)),
                ('isbn_add_code', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lib_information',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LibSA',
            fields=[
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('a_key', models.CharField(max_length=700, primary_key=True, serialize=False)),
                ('author', models.TextField(blank=True, null=True)),
                ('ebook', models.TextField(blank=True, null=True)),
                ('subject', models.TextField(blank=True, db_column='SUBJECT', null=True)),
                ('price', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lib_s_a',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('level_0', models.BigIntegerField(blank=True, null=True)),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('date', models.CharField(max_length=700, primary_key=True, serialize=False)),
                ('year', models.BigIntegerField(blank=True, null=True)),
                ('month', models.FloatField(blank=True, null=True)),
                ('week', models.FloatField(blank=True, null=True)),
                ('day', models.FloatField(blank=True, null=True)),
                ('pub_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'period',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reputation',
            fields=[
                ('level_0', models.BigIntegerField(blank=True, null=True)),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('itemkey', models.CharField(max_length=700, primary_key=True, serialize=False)),
                ('rank', models.FloatField(blank=True, null=True)),
                ('review_num', models.TextField(blank=True, null=True)),
                ('review_rate', models.TextField(blank=True, null=True)),
                ('new1', models.TextField(blank=True, null=True)),
                ('portal', models.ForeignKey(blank=True, db_column='portal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.buyc')),
            ],
            options={
                'db_table': 'reputation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BookTable',
            fields=[
                ('level_0', models.BigIntegerField(primary_key=True, serialize=False)),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('date', models.ForeignKey(blank=True, db_column='date', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.period')),
                ('itemkey', models.ForeignKey(blank=True, db_column='itemkey', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.reputation')),
                ('title', models.ForeignKey(blank=True, db_column='title', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.information')),
            ],
            options={
                'db_table': 'book_table',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LibTable',
            fields=[
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('a_key', models.OneToOneField(db_column='a_key', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='home.libsa')),
                ('author', models.TextField(blank=True, null=True)),
                ('pub', models.ForeignKey(blank=True, db_column='pub', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.libdate')),
                ('title', models.ForeignKey(blank=True, db_column='title', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.libinformation')),
            ],
            options={
                'db_table': 'lib_table',
                'managed': True,
            },
        ),
    ]
